vscode:
  extensions:
    - christian-kohler.path-intellisense@1.4.2:QnOrf5fk6KiVaQs4cNEP+w==
    - dracula-theme.theme-dracula@2.21.0:RtzqaQieYebr5vxh8cZ+pQ==
    - humao.rest-client@0.23.2:EcQzdx/LsXrhATjZFVSutw==
    - dsznajder.es7-react-js-snippets@2.7.1:ot1GSdt45abTrr2DCAM42g==
    - esbenp.prettier-vscode@3.20.0:37/f4uBlE287wUjENFq1aA==
    - CoenraadS.bracket-pair-colorizer@1.0.61:fqPT1sJEqaEdrfXeYbdW+A==
    - ms-vscode.cpptools@0.27.0:z/UThvtoloHQ3y4wv5ptAw==